name: Deploy to DigitalOcean Droplet

on:
  push:
    branches: [main, master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up SSH key
      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DO_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519

      # Add server to known_hosts
      - name: Add server to known_hosts
        run: |
          ssh-keyscan -H ${{ secrets.DO_SERVER_IP }} >> ~/.ssh/known_hosts

      # Sync changed files to the server using rsync
      - name: Sync changed files to server
        run: |
          rsync -avz --exclude '.git/' --exclude 'node_modules/' -e "ssh -i ~/.ssh/id_ed25519" ./ root@${{ secrets.DO_SERVER_IP }}:/root/project

      # Deploy and restart Docker services on the server
      - name: Deploy to Droplet
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.DO_SERVER_IP }}
          username: root
          key: ${{ secrets.DO_PRIVATE_KEY }}
          script: |
            cd /root/project
            git reset --hard
            git pull origin main
            docker pull ${{ secrets.DOCKER_USERNAME }}/moodify:latest
            docker stop flask-app || true
            docker rm flask-app || true
            docker-compose -f /root/project/back-end/docker-compose.yml down || true
            docker-compose -f /root/project/back-end/docker-compose.yml up --build -d
