name: Deploy to DigitalOcean Droplet

on:
  push:
    branches: [main, master]
  pull_request:
    types: [opened, closed]
    branches: [main, master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and push Docker image
      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/moodify:latest -f ./back-end/Dockerfile ./back-end
          docker push ${{ secrets.DOCKER_USERNAME }}/moodify:latest

      # Deploy to DigitalOcean Droplet
      - name: Deploy to Droplet
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.DO_SERVER_IP }}
          username: ${{ secrets.DO_USER }}
          key: ${{ secrets.DO_PRIVATE_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/moodify:latest
            docker stop flask-app || true
            docker rm flask-app || true
            docker-compose -f ~/project/back-end/docker-compose.yml down || true
            docker-compose -f ~/project/back-end/docker-compose.yml up --build -d
